server:
  port: 8080

spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=identity_service;encrypt=true;trustServerCertificate=true"
    username: sa
    password: 123456789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      # Đây là lệnh tự động tạo bảng
      ddl-auto: update

    properties:
      hibernate:
        # Bật show_sql để xem log
        show_sql: true
        # Bạn có thể bật dòng này để format SQL cho dễ đọc
        # format_sql: true